/* this is script for creating a bronze layer */

CREATE OR ALTER PROCEDURE bronze.load_bronze AS
BEGIN
   DECLARE @start_time DATETIME , @end_time DATETIME;
   BEGIN TRY
		 PRINT '===================================================';
		 PRINT 'Loading Bronze Layer';
		 PRINT '===================================================';

		 PRINT'----------------------------------------------------';
		 PRINT 'LOADING CRM SECTION';
		 PRINT'----------------------------------------------------';

        SET @start_time = GETDATE();
		PRINT ' >> TRUNCATING TABLE : bronze.crm_cust_info';
		TRUNCATE TABLE bronze.crm_cust_info;

		PRINT 'INSERTING DATA INTO : bronze.crm_cust_info';
		BULK INSERT bronze.crm_cust_info
		FROM 'C:\Users\LENOVO\Desktop\data warehouse\sql-data-warehouse-project\datasets\source_crm\cust_info.csv'
		WITH(
		FIRSTROW = 2,
		FIELDTERMINATOR = ',',
		TABLOCK
		);
		 SET @end_time = GETDATE();
		 PRINT'>> Load Duration : ' + CAST( DATEDIFF(second , @start_time , @end_time) AS NVARCHAR ) + ' seconds' ;
		 PRINT'-----------------------';


        SET @start_time = GETDATE(); 
		PRINT ' >> TRUNCATING TABLE :  bronze.crm_prd_info';
		TRUNCATE TABLE bronze.crm_prd_info;

		PRINT 'INSERTING DATA INTO : bronze.crm_prd_info';
		BULK INSERT bronze.crm_prd_info
		FROM 'C:\Users\LENOVO\Desktop\data warehouse\sql-data-warehouse-project\datasets\source_crm\prd_info.csv'
		WITH(
		FIRSTROW = 2 ,
		FIELDTERMINATOR = ',',
		TABLOCK
		);
		 SET @end_time = GETDATE();
		 PRINT'>> Load Duration : ' + CAST( DATEDIFF(second , @start_time , @end_time) AS NVARCHAR ) + ' seconds' ;
		 PRINT'-----------------------';

        SET @start_time = GETDATE();
		PRINT ' >> TRUNCATING TABLE : bronze.crm_sales_details';
		TRUNCATE TABLE bronze.crm_sales_details;

		PRINT 'INSERTING DATA INTO : bronze.crm_sales_details';
		BULK INSERT bronze.crm_sales_details
		FROM 'C:\Users\LENOVO\Desktop\data warehouse\sql-data-warehouse-project\datasets\source_crm\sales_details.csv'
		WITH(
		FIRSTROW = 2 ,
		FIELDTERMINATOR = ',',
		TABLOCK
		);
		 SET @end_time = GETDATE();
		 PRINT'>> Load Duration : ' + CAST( DATEDIFF(second , @start_time , @end_time) AS NVARCHAR ) + ' seconds' ;
		 PRINT'-----------------------';

		 PRINT'----------------------------------------------------';
		 PRINT 'LOADING ERP SECTION';
		 PRINT'----------------------------------------------------';
        
    	 SET @start_time = GETDATE();
		PRINT ' >> TRUNCATING TABLE : bronze.erp_cust_az12';
		TRUNCATE TABLE bronze.erp_cust_az12;

		PRINT 'INSERTING DATA INTO :  bronze.erp_cust_az12';
		BULK INSERT bronze.erp_cust_az12
		FROM 'C:\Users\LENOVO\Desktop\data warehouse\sql-data-warehouse-project\datasets\source_erp\CUST_AZ12.csv'
		WITH(
		FIRSTROW = 2 ,
		FIELDTERMINATOR = ',',
		TABLOCK
		);
		 SET @end_time = GETDATE();
		 PRINT'>> Load Duration : ' + CAST( DATEDIFF(second , @start_time , @end_time) AS NVARCHAR ) + ' seconds' ;
		 PRINT'-----------------------';
        
		 SET @start_time = GETDATE();
		PRINT ' >> TRUNCATING TABLE :  bronze.erp_loc_a101';
		TRUNCATE TABLE bronze.erp_loc_a101;

		PRINT 'INSERTING DATA INTO :  bronze.erp_loc_a101';
		BULK INSERT bronze.erp_loc_a101
		FROM 'C:\Users\LENOVO\Desktop\data warehouse\sql-data-warehouse-project\datasets\source_erp\LOC_A101.csv'
		WITH(
		FIRSTROW = 2 ,
		FIELDTERMINATOR = ',',
		TABLOCK
		);
		 SET @end_time = GETDATE();
		 PRINT'>> Load Duration : ' + CAST( DATEDIFF(second , @start_time , @end_time) AS NVARCHAR ) + ' seconds' ;
		 PRINT'-----------------------';

		 SET @start_time = GETDATE();
		PRINT ' >> TRUNCATING TABLE : bronze.erp_px_cat_g1v2';
		TRUNCATE TABLE bronze.erp_px_cat_g1v2;

		PRINT 'INSERTING DATA INTO : bronze.erp_px_cat_g1v2';
		BULK INSERT bronze.erp_px_cat_g1v2
		FROM 'C:\Users\LENOVO\Desktop\data warehouse\sql-data-warehouse-project\datasets\source_erp\PX_CAT_G1V2.csv'
		WITH(
		FIRSTROW = 2 ,
		FIELDTERMINATOR = ',',
		TABLOCK
		);
		 SET @end_time = GETDATE();
		 PRINT'>> Load Duration : ' + CAST( DATEDIFF(second , @start_time , @end_time) AS NVARCHAR ) + ' seconds' ;
		 PRINT'-----------------------';
     END TRY
	 BEGIN CATCH
	       PRINT'===================================================='
		   PRINT'ERROR OCCURED DURING LOADING BRONZE LAYER'
		   PRINT'===================================================='
     END CATCH
END


